version: "2"

volumes:
  local_metabase_data: {}

services:
  metabase:
    image: metabase/metabase
    container_name: bolid_local_metabase
    volumes:
      - local_metabase_data:/metabase-data
    environment:
      - VIRTUAL_HOST=metabase.bolid.local
      - LETSENCRYPT_HOST=metabase.bolid.local
      - MB_DB_FILE=/metabase-data/metabase.db
    networks:
      - nginxproxy_local_network
      - bolid_api_local_network
    expose:
      - "3000"

networks:
  nginxproxy_local_network:
    external: true
  bolid_api_local_network:
    external: true
