version: "2"

volumes:
  bolid_dashboard_local_metabase_data:
    name: bolid_dashboard_local_metabase_data
  bolid_dashboard_local_metabase_backups:
    name: bolid_dashboard_local_metabase_backups

services:
  metabase:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: bolid_dashboard_local_metabase
    container_name: bolid_dashboard_local_metabase
    volumes:
      - ./metabase:/usr/local/bin
      - bolid_dashboard_local_metabase_data:/data
      - bolid_dashboard_local_metabase_backups:/backups
    env_file:
      - ./.envs/.metabase
    environment:
      - VIRTUAL_HOST=dashboard.bolid.local
      - VIRTUAL_PORT=3000
    networks:
      - bolid_nginxproxy_local_network
      # - bolid_api_local_network

networks:
  bolid_nginxproxy_local_network:
    external: true
  # bolid_api_local_network:
  #  external: true
