version: "2"

volumes:
  bolid_dashboard_production_metabase_data:
    name: bolid_dashboard_production_metabase_data
  bolid_dashboard_production_metabase_backups:
    name: bolid_dashboard_production_metabase_backups

services:
  metabase:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: bolid_dashboard_production_metabase
    container_name: bolid_dashboard_production_metabase
    volumes:
      - bolid_dashboard_production_metabase_data:/data
      - bolid_dashboard_production_metabase_backups:/backups
    env_file:
      - ./.envs/.metabase
    environment:
      - VIRTUAL_HOST=dashboard.bolid.be
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=dashboard.bolid.be
    networks:
      - bolid_nginxproxy_production_network

networks:
  bolid_nginxproxy_production_network:
    external: true
